# yamllint disable rule:line-length
---
name: install

description: install gha-tools dependencies

inputs:

  op-version:
    description: 1password-cli version
    required: false
    default: ""

  teller-version:
    description: Install Teller version
    required: false
    default: ""

  vault-version:
    description: Install Vault version
    required: false
    default: ""

  buildevents-version:
    description: Install Snyk version
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: Install 1Password CLI
      if: ${{ inputs.op-version != '' }}
      uses: 1password/install-cli-action@v1
      with:
        version: ${{ inputs.op-version }}

    - name: Install Teller
      if: ${{ inputs.teller-version != '' }}
      shell: bash
      run: |
        curl -L https://github.com/tellerops/teller/releases/download/v${{ inputs.teller-version }}/teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz --output teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz
        tar -xzf teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz
        sudo mv teller /usr/local/bin/teller
        rm teller_${{ inputs.teller-version }}_Linux_x86_64.tar.gz

    - name: Install Vault
      if: ${{ inputs.vault-version != '' }}
      shell: bash
      run: |
        curl -SLO "https://releases.hashicorp.com/vault/${{ inputs.vault-version }}/vault_${{ inputs.vault-version }}_linux_amd64.zip" > "vault_${{ inputs.vault-version }}_linux_amd64.zip"
        sudo unzip "vault_${{ inputs.vault-version }}_linux_amd64.zip" -d /usr/local/bin
        sudo rm "vault_${{ inputs.vault-version }}_linux_amd64.zip"

    - name: Install buildevents
      if: ${{ inputs.buildevents-version != '' }}
      shell: bash
      run: |
        curl -L -o buildevents https://github.com/honeycombio/buildevents/releases/download/v${{ inputs.buildevents-version }}/buildevents-linux-amd64
        chmod +x buildevents
        sudo mv buildevents /usr/local/bin/buildevents
