# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: integration tests

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

permissions:
  contents: read

jobs:

  integration-tests:
    name: action integration tests
    runs-on: ubuntu-latest

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b         # v4.1.5

      - name: install base-image packages as Action
        uses: ThoughtWorks-DPS/base-packages-action@main
        with:
          op-version: 2.28.0
          teller-version: 1.5.6
          vault-version: 1.16.2
          buildevents-version: 0.16.0

      - name: test base-packages-action results
        shell: bash
        run: |
          set -exo pipefail
          op --version | grep "2.28.0"
          teller version | grep "1.5.6"
          vault --version | grep "1.16.2"
          buildevents --version | grep "0.16.0"
